### ISSUE TITLE
Path seperator

### ISSUE THREAD

**Issue by Nananas** [luboslenco/fox_blender#2]
Hi again

Just a quick note that using `"\"` as path seperator in `s = bpy.data.filepath.split("\")` does not work on my Windows 8, as it returns a path full of `\\`-s.

Maybe use `os.sep` to be platform-independent?

**Comment by luboslenco** [comment]
Good catch, never tried on Windows so far. Actually need to make build buttons platform independent also..

Thanks for your input it's really helpful.

**Comment by Nananas** [comment]
I don't know if I should make a new issue of this as it probably is a platform dependent problem ...:

Calling the following in `buildProject()` isn't working on Windows (obviously :innocent: ):
```
470~ |     bashCommand = "Kha/Tools/hake/hake-osx ..."
```
I get the following error: `'Kha' is not recognized as an internal or external command,
operable program or batch file.`.

But this works:
```
470~ |     bashCommand = "start /b /w Kha/Tools/hake/hake.exe ..."
```
(As seen in the Kha `build.bat` file)
This is not platform independent though.

**Comment by luboslenco** [comment]
Path separator should be fixed(thanks) and buildProject() should also work, at least for Windows and Html5 targets.

Run and Project buttons are not yet implemented though.
